#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gradingStudents' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY grades as parameter.
#

def gradingStudents(grades):
         # Write your code here
        for i in range(len(grades)):
            num = grades[i]
            not_true = True
            while not_true:
                if num % 5 == 0:
                    break
                num += 1
            if abs(grades[i] - num) < 3:
                if num >= 40:
                    grades[i] = num
                    continue 
                

        
    
        return grades
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    grades_count = int(input().strip())

    grades = []

    for _ in range(grades_count):
        grades_item = int(input().strip())
        grades.append(grades_item)

    result = gradingStudents(grades)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
